export const visualTokens = {
    colors: {
        backgroundRoot: '#070A10',
        backgroundElevated: '#0A1018',
        surface1: '#0F1623',
        surface2: '#121A29',
        surface3: '#182234',
        borderSubtle: '#1B2637',
        borderStrong: '#263349',
        textPrimary: '#F3F7FF',
        textSecondary: '#B8C2D9',
        textMuted: '#7E8AA3',
        textDisabled: '#5B6579',
        primary: '#6D5DF6',
        primaryHover: '#7C70FF',
        cyanAccent: '#06B6D4',
        pinkAccent: '#E11D48',
        success: '#22C55E',
        warning: '#F59E0B',
        danger: '#EF4444',
        overlaySoft: 'rgba(7, 10, 16, 0.62)',
        overlayStrong: 'rgba(7, 10, 16, 0.82)',
    },
    backgrounds: {
        app: 'radial-gradient(1200px 400px at 20% -10%, rgba(225, 29, 72, 0.18), transparent 60%), radial-gradient(900px 320px at 95% 2%, rgba(14, 116, 144, 0.22), transparent 62%), linear-gradient(180deg, #070a10 0%, #0a1018 100%)',
        panel: 'linear-gradient(180deg, rgba(18, 26, 41, 0.94) 0%, rgba(15, 22, 35, 0.98) 100%)',
        panelElevated:
            'linear-gradient(180deg, rgba(24, 34, 52, 0.96) 0%, rgba(18, 26, 41, 0.94) 100%)',
    },
    spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
    },
    radius: {
        sm: '10px',
        md: '14px',
        lg: '18px',
        xl: '24px',
        pill: '999px',
    },
    typography: {
        pageTitle: '1.5rem',
        pageSubtitle: '0.875rem',
        sectionTitle: '1.125rem',
    },
    shadow: {
        card: '0 8px 30px rgba(0, 0, 0, 0.24)',
        floating: '0 12px 40px rgba(0, 0, 0, 0.35)',
        activeGlowPrimary: '0 0 0 1px rgba(109, 93, 246, 0.6), 0 8px 30px rgba(109, 93, 246, 0.18)',
        layered: '0 1px 2px rgba(0,0,0,0.1), 0 4px 8px rgba(0,0,0,0.1), 0 16px 32px rgba(0,0,0,0.1)',
    },
    glass: {
        medium: {
            background: 'rgba(18, 26, 41, 0.7)',
            backdropFilter: 'blur(12px)',
        },
        strong: {
            background: 'rgba(15, 22, 35, 0.85)',
            backdropFilter: 'blur(16px)',
        },
    },
    layout: {
        sidebarWidth: '240px',
        sidebarWidthCollapsed: '80px',
        headerHeight: '64px',
        headerHeightMobile: '56px',
        bottomNavHeight: '64px',
        contentMaxWidth: '1440px',
    },
    motion: {
        fast: '160ms',
        base: '220ms',
        slow: '300ms',
    },
} as const;

export const appCssVariables = {
    '--app-color-background-root': visualTokens.colors.backgroundRoot,
    '--app-color-background-elevated': visualTokens.colors.backgroundElevated,
    '--app-color-surface-1': visualTokens.colors.surface1,
    '--app-color-surface-2': visualTokens.colors.surface2,
    '--app-color-surface-3': visualTokens.colors.surface3,
    '--app-color-border-subtle': visualTokens.colors.borderSubtle,
    '--app-color-border-strong': visualTokens.colors.borderStrong,
    '--app-color-text-primary': visualTokens.colors.textPrimary,
    '--app-color-text-secondary': visualTokens.colors.textSecondary,
    '--app-color-text-muted': visualTokens.colors.textMuted,
    '--app-color-text-disabled': visualTokens.colors.textDisabled,
    '--app-color-primary': visualTokens.colors.primary,
    '--app-color-primary-hover': visualTokens.colors.primaryHover,
    '--app-color-cyan-accent': visualTokens.colors.cyanAccent,
    '--app-color-pink-accent': visualTokens.colors.pinkAccent,
    '--app-color-success': visualTokens.colors.success,
    '--app-color-warning': visualTokens.colors.warning,
    '--app-color-danger': visualTokens.colors.danger,
    '--app-color-overlay-soft': visualTokens.colors.overlaySoft,
    '--app-color-overlay-strong': visualTokens.colors.overlayStrong,
    '--app-background-app': visualTokens.backgrounds.app,
    '--app-background-panel': visualTokens.backgrounds.panel,
    '--app-background-panel-elevated': visualTokens.backgrounds.panelElevated,
    '--app-spacing-1': visualTokens.spacing[1],
    '--app-spacing-2': visualTokens.spacing[2],
    '--app-spacing-3': visualTokens.spacing[3],
    '--app-spacing-4': visualTokens.spacing[4],
    '--app-spacing-5': visualTokens.spacing[5],
    '--app-spacing-6': visualTokens.spacing[6],
    '--app-spacing-8': visualTokens.spacing[8],
    '--app-spacing-10': visualTokens.spacing[10],
    '--app-spacing-12': visualTokens.spacing[12],
    '--app-spacing-16': visualTokens.spacing[16],
    '--app-radius-sm': visualTokens.radius.sm,
    '--app-radius-md': visualTokens.radius.md,
    '--app-radius-lg': visualTokens.radius.lg,
    '--app-radius-xl': visualTokens.radius.xl,
    '--app-radius-pill': visualTokens.radius.pill,
    '--app-font-page-title': visualTokens.typography.pageTitle,
    '--app-font-page-subtitle': visualTokens.typography.pageSubtitle,
    '--app-font-section-title': visualTokens.typography.sectionTitle,
    '--app-shadow-card': visualTokens.shadow.card,
    '--app-shadow-floating': visualTokens.shadow.floating,
    '--app-shadow-active-primary': visualTokens.shadow.activeGlowPrimary,
    '--app-shadow-layered': visualTokens.shadow.layered,
    '--app-glass-medium-background': visualTokens.glass.medium.background,
    '--app-glass-medium-backdrop': visualTokens.glass.medium.backdropFilter,
    '--app-glass-strong-background': visualTokens.glass.strong.background,
    '--app-glass-strong-backdrop': visualTokens.glass.strong.backdropFilter,
    '--app-shell-sidebar-width': visualTokens.layout.sidebarWidth,
    '--app-shell-sidebar-width-collapsed': visualTokens.layout.sidebarWidthCollapsed,
    '--app-shell-header-height': visualTokens.layout.headerHeight,
    '--app-shell-header-height-mobile': visualTokens.layout.headerHeightMobile,
    '--app-shell-bottom-nav-height': visualTokens.layout.bottomNavHeight,
    '--app-content-max-width': visualTokens.layout.contentMaxWidth,
    '--app-motion-fast': visualTokens.motion.fast,
    '--app-motion-base': visualTokens.motion.base,
    '--app-motion-slow': visualTokens.motion.slow,
} as const;
